export default {
	handPoints: {
		highestCard: 1,
		pair: 2,
		twoPairs: 3,
		tris: 4,
		straight: 5,
		flush: 6,
		fullHouse: 7,
		poker: 8,
		straightFlush: 9
	},
	figureValues: {
		"2": 2,
		"3": 3,
		"4": 4,
		"5": 5,
		"6": 6,
		"7": 7,
		"8": 8,
		"9": 9,
		"T": 10,
		"J": 11,
		"Q": 12,
		"K": 13,
		"A": 14,
	},
	combinationsNames: {
		"highestCard": "high card",
		"pair": "pair",
		"twoPairs": "two pairs",
		"tris": "tris",
		"straight": "straight",
		"flush": "flush",
		"fullHouse": "full house",
		"poker": "four of a kind",
		"straightFlush": "straight flush",
	},
	figureNames: {
		"2": "2",
		"3": "3",
		"4": "4",
		"5": "5",
		"6": "6",
		"7": "7",
		"8": "8",
		"9": "9",
		"T": "10",
		"J": "Jack",
		"Q": "Queen",
		"K": "King",
		"A": "Ace",
	},
	suitNames: {
		"C": "clubs",
		"D": "diamonds",
		"H": "hearts",
		"S": "spades"
	}
}